spring:
  #  thymeleaf:
  #    mode: HTML
  #    encoding: UTF-8
  #    servlet:
  #      content-type: text/html
  #    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: 123456
    #type: com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource
#mybatis:
#  mapper-locations: classpath:mappers/*.xml
  redis:
    database: 0
    host: 192.168.0.4
    password:
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
    timeout: 0